main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('tasks/', views.tasks_index, name='index'),
    path('tasks/<int:task_id>/', views.task_detail, name='detail'),
    path('tasks/create/', views.TaskCreate.as_view(), name='tasks_create'),
    path('tasks/<int:pk>/update/', views.TaskUpdate.as_view(), name='tasks_update'),
    path('tasks/<int:pk>/delete/', views.TaskDelete.as_view(), name='tasks_delete'),
    path('tasks/<int:task_id>/status_update/', views.status_update, name='status_update'),
    path('tasks/<int:task_id>/assoc_team_members/<int:team_member_id>/', views.assoc_team_members, name='assoc_team_members'),
    path('tasks/<int:task_id>/remove_team_members/<int:team_member_id>/', views.remove_team_members, name='remove_team_members'),
    # Team Member URLs
    path('team_members/', views.team_list, name='team_index'),
    path('team_members/<int:pk>/', views.TeamDetail.as_view(), name='team_detail'),
    path('team_members/create/', views.TeamCreate.as_view(), name='team_create'),
    path('team_members/<int:pk>/update/', views.TeamUpdate.as_view(), name='team_update'),
    path('team_members/<int:pk>/delete/', views.TeamDelete.as_view(), name='team_delete'),
    # Team Member Photo URL
    path('team_members/<int:team_member_id>/add_photo/', views.add_photo, name='add_photo'),
    # User signup URL
    path('accounts/signup/', views.signup, name='signup')
]

taskcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

STATUS = (
    ('U', 'Unassigned'),
    ('N', 'Assigned - Not Done'),
    ('F', 'Assigned - Finished'),
)

# Create your models here.
class Team_Member(models.Model):
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
      return f'{self.name}'

    def get_absolute_url(self):
      return reverse('team_detail', kwargs={'pk': self.id})


class Task(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=250)
    due_date = models.DateField('due date')

    team_members = models.ManyToManyField(Team_Member)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
      return reverse('detail', kwargs={'task_id': self.id})


class Status(models.Model):
    status = models.CharField(
      max_length=1,
      choices=STATUS,
      default=STATUS[0][0]
    )

    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
      return f"{self.get_status_display()}"

class Photo(models.Model):
  url = models.CharField(max_length=200)
  team_member = models.ForeignKey(Team_Member, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for team_member_id: {self.team_member_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Status

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['status']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

# Imports for creating User Signup Page
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Imports login_required decorator for custom defined views
from django.contrib.auth.decorators import login_required

# Imports LoginRequiredMixin for class based views
from django.contrib.auth.mixins import LoginRequiredMixin

# Import Custom Models
from .models import Task, Status, Team_Member, Photo

from .forms import StatusForm

# import for S3 photo upload
import uuid
import boto3

# Constants for S3 photo upload
S3_BASE_URL='https://S3.us-east-1.amazonaws.com/'
BUCKET = 'taskcollector'

# Create your views here.
from django.http import HttpResponse

def signup(request):
    error_message = ''
    if request.method == 'POST':
        #If signup filled form has been submited run the folowing code
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # If the form has been filled out correctly create the user
            user = form.save()
            # This will login in the user so they don't have to re-login after signup
            login(request,user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up, please try again'
    # If request.method was abad POST or a GET request, render signup.html with empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['name','description','due_date']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    status_form = StatusForm()
    fields = ['description', 'due_date']

class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = '/tasks/'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def tasks_index(request):
    tasks = Task.objects.filter(user=request.user)
    return render(request, 'tasks/index.html', { 'tasks': tasks })

@login_required
def task_detail(request, task_id):
    task = Task.objects.get(id=task_id)
    user_team = Team_Member.objects.filter(user=request.user)
    if task.status_set.count() == 0:
        Status.objects.create(status='U',task=task)
    team_members_not_assigned = user_team.exclude(id__in = task.team_members.all().values_list('id'))
    status_form = StatusForm()
    return render(request, 'tasks/detail.html', { 
        'task':task, 
        'status_form':status_form,
        'available_team_members': team_members_not_assigned
     })

@login_required
def assoc_team_members(request, task_id, team_member_id):
    Task.objects.get(id=task_id).team_members.add(team_member_id)
    return redirect('detail', task_id=task_id)

@login_required
def remove_team_members(request, task_id, team_member_id):
    Task.objects.get(id=task_id).team_members.remove(team_member_id)
    return redirect('detail', task_id=task_id)

@login_required
def status_update(request, task_id):
    form = StatusForm(request.POST)
    s = Task.objects.get(id=task_id).status_set.first()
    if form.is_valid():
        updated_status = form.cleaned_data['status']
        Status.objects.filter(pk=s.id).update(status=updated_status)
    return redirect('detail', task_id=task_id)


#class TeamList(LoginRequiredMixin, ListView):
#    model = Team_Member

@login_required
def team_list(request):
    team = Team_Member.objects.filter(user=request.user)
    return render(request, 'main_app/team_member_list.html', { 'team_member_list': team })

class TeamDetail(LoginRequiredMixin, DetailView):
   model = Team_Member

class TeamCreate(LoginRequiredMixin, CreateView):
    model = Team_Member
    fields = ['name','role']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class TeamUpdate(LoginRequiredMixin, UpdateView):
    model = Team_Member
    fields = ['name','role']

class TeamDelete(LoginRequiredMixin, DeleteView):
    model = Team_Member
    success_url = '/team_members/'

@login_required
def add_photo(request, team_member_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # The next line of code creates a unique 'key' for S3 and adds file extension with +
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # The next line of code builds the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # If Team Member already has photo, replace the photo with the new updated one
            tm = Team_Member.objects.get(id=team_member_id)
            if tm.photo_set.count():
                current_photo = tm.photo_set.first()
                Photo.objects.filter(id=current_photo.id).update(url=url)
            else:
                photo = Photo(url=url, team_member_id=team_member_id)
                photo.save()
        except:
            print('An error occured uploading file to S3')
    return redirect('/team_members', team_member_id=team_member_id)

main_app/templates/main_app/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<p class="headline pageTop">Delete Task</p>

<h4>Are you sure you want to delete <span class="deep-orange-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/task_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <p class="headline pageTop">Edit <u><i>{{object.name}}</i></u></p>
{% else %}
    <p class="headline pageTop">Add Task</p>
{% endif %}



<form action="" method="post">
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

<script>
    var dateEl = document.getElementById('id_due_date')
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true,
    });
</script>
{% endblock %}

main_app/templates/main_app/team_member_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <p class="headline pageTop">Delete Team Member</p>

    <h4>Are you sure you want to delete <span class="deep-orange-text">{{ object.name }}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm Deletion!" class="btn">
        <a href="{% url 'team_detail' object.id %}"></a>
    </form>
{% endblock %}

main_app/templates/main_app/team_member_detail.html
{% extends 'base.html' %}
{% block content %}

<p class="center pageTop topLabel">Team Member Details</p>

<div class="row">
    <!-- Team Member Details -->
    <div class="col s6 col-offset-3">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ team_member.name }}</span>
                <p><blockquote>Role: {{ team_member.role }}</blockquote></p>
                <hr>
                <span class="card-title"><label> Assigned to:</label></span>
                {% for task in team_member.task_set.all %}
                    <!-- TRY TO ADD STATUS WITH CLASS=RIGHT -->
                    <p>{{task.name}}</p>
                {% endfor %}
            </div>
            <div class="card-action">
                <a href="{% url 'team_update' team_member.id %}">Edit</a>
                <a href="{% url 'team_delete' team_member.id %}">Delete</a>
            </div>
        </div>
    </div>

<!-- Team Member Photo -->
    <div class="col s6">
        <div class="card">
        
            {% if team_member.photo_set.count %}
                <div class="center-align"><img src="{{ team_member.photo_set.first.url }}" alt="Picture of team member {{ team_member.name }}" class="responsive-img photo"></div>
            {% else %}
                <div class="card-panel center-align"><label>{{ team_member.name }} has no photo</label></div>
            {% endif %}

            <!-- Form to Add Team Member Photo -->
            <form action="{% url 'add_photo' team_member.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
                {% csrf_token %}
                <input type="file" name="photo-file">
                <br><br>
                <input type="submit" value="Upload Photo" class="btn">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/team_member_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <p class="headline">Edit Team Member</p>
{% else %}
    <p class="headline">Add Team Member</p>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/team_member_list.html
{% extends 'base.html' %}
{% block content %}

<p class="headline pageTop">Team Members</p>

{% if not team_member_list %}
    <div class="text">
        <span class="txt2">
            <p class="blurb">You don't have any team members yet.</p> 
            <p class="blurb">Click on '<u><a href="{% url 'team_create' %}">Add Team Member</a></u>' to start adding them to your project.</p>
        </span>
    </div>
{% endif %}

{% for member in team_member_list %}
    <a href="{% url 'team_detail' member.id %}">
        <div class="card">
            <div class="card-content">
                {% if member.photo_set.count %}
                <img src="{{ member.photo_set.first.url }} " height="75px" style="padding-right:20px" alt="" class=" left">
                {% endif %}
                <span class="card-title">{{ member.name }}</span>
                <h6>Role: {{ member.role }}</h4>
                </div>
        </div>
    </a>

{% endfor %}

{% endblock %}